<?php

namespace Glamstack\GoogleCloud\Tests\Fakes;

use Glamstack\GoogleCloud\Resources\BaseClient;

class BaseClientFake extends BaseClient
{
    public function parseConfigFile(string $connection_key): array
    {
        return parent::parseConfigFile($connection_key); // TODO: Change the autogenerated stub
    }

    public function getConfigApiScopes(string $connection_key)
    {
        return parent::getConfigApiScopes($connection_key); // TODO: Change the autogenerated stub
    }

    public function getConfigSubjectEmail(string $connection_key)
    {
        return parent::getConfigSubjectEmail($connection_key); // TODO: Change the autogenerated stub
    }

    public function getConfigJsonFilePath(string $connection_key)
    {
        return parent::getConfigJsonFilePath($connection_key); // TODO: Change the autogenerated stub
    }

    public function parseConnectionConfigArray(array $connection_config)
    {
        return parent::parseConnectionConfigArray($connection_config); // TODO: Change the autogenerated stub
    }

    public function getConfigArrayApiScopes(array $connection_config)
    {
        return parent::getConfigArrayApiScopes($connection_config); // TODO: Change the autogenerated stub
    }

    public function getConfigArraySubjectEmail(array $connection_config)
    {
        return parent::getConfigArraySubjectEmail($connection_config); // TODO: Change the autogenerated stub
    }

    public function getConfigArrayFilePath(array $connection_config)
    {
        return parent::getConfigArrayFilePath($connection_config); // TODO: Change the autogenerated stub
    }

    public function getConfigArrayJsonKey(array $connection_config)
    {
        return parent::getConfigArrayJsonKey($connection_config); // TODO: Change the autogenerated stub
    }
}